# Generated by Django 5.1.4 on 2025-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('sname', models.CharField(max_length=50)),
                ('spno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
